/**
 * LockfileManager Property-Based Tests
 * 
 * Property-based tests for the LockfileManager service using fast-check.
 * These tests verify correctness properties that should hold for all valid inputs.
 * 
 * Properties covered:
 * - Property 2: Lockfile Schema Validation (Requirements 4.2-4.7, 11.1-11.4, 15.1-15.2)
 * - Property 3: Lockfile Round-Trip Consistency (Requirements 4.1, 5.2, 5.5)
 * - Property 7: Checksum Modification Detection (Requirements 14.1-14.3)
 * - Property 12: Source and Hub Configuration Completeness (Requirements 12.1-12.6)
 * - Property 15: Atomic Lockfile Write (Requirements 15.6)
 */

import * as fc from 'fast-check';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import {
    LockfileBuilder,
    LockfileGenerators,
    createMockLockfile,
    LOCKFILE_DEFAULTS
} from '../helpers/lockfileTestHelpers';
import { PropertyTestConfig } from '../helpers/propertyTestHelpers';
import { Lockfile } from '../../src/types/lockfile';
import { SchemaValidator } from '../../src/services/SchemaValidator';

describe('LockfileManager Property Tests', () => {
    let tempDir: string;
    let schemaValidator: SchemaValidator;
    const lockfileSchemaPath = path.join(process.cwd(), 'schemas', 'lockfile.schema.json');

    // ===== Test Utilities =====
    const createTempDir = (): string => {
        const dir = path.join(__dirname, '..', '..', 'test-temp-lockfile-prop-' + Date.now());
        fs.mkdirSync(dir, { recursive: true });
        return dir;
    };

    const cleanupTempDir = (dir: string): void => {
        if (fs.existsSync(dir)) {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    };

    beforeEach(() => {
        tempDir = createTempDir();
        schemaValidator = new SchemaValidator(process.cwd());
    });

    afterEach(() => {
        cleanupTempDir(tempDir);
        schemaValidator.clearCache();
    });

    /**
     * Property 2: Lockfile Schema Validation
     * 
     * For any lockfile generated by the extension, it SHALL be valid JSON with
     * required fields ($schema, version, generatedAt, generatedBy, bundles, sources)
     * and use 2-space indentation.
     * 
     * **Validates: Requirements 4.2-4.7, 11.1-11.4, 15.1-15.2**
     */
    describe('Property 2: Lockfile Schema Validation', () => {
        it('generated lockfiles should be valid against JSON schema', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Validate against JSON schema
                        const result = await schemaValidator.validate(lockfile, lockfileSchemaPath);
                        
                        // Property: All generated lockfiles should be schema-valid
                        expect(result.valid, `Schema validation failed: ${result.errors.join(', ')}`).toBe(true);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('lockfiles should have all required fields', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.lockfile({ minBundles: 0, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Property: All required fields must be present
                        expect(lockfile.$schema, 'Missing $schema field').toBeTruthy();
                        expect(lockfile.version, 'Missing version field').toBeTruthy();
                        expect(lockfile.generatedAt, 'Missing generatedAt field').toBeTruthy();
                        expect(lockfile.generatedBy, 'Missing generatedBy field').toBeTruthy();
                        expect(lockfile.bundles !== undefined, 'Missing bundles field').toBeTruthy();
                        expect(lockfile.sources !== undefined, 'Missing sources field').toBeTruthy();
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('version field should be semver-compatible', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.lockfile(),
                    async (lockfile: Lockfile) => {
                        // Property: Version should match semver pattern
                        const semverPattern = /^\d+\.\d+\.\d+$/;
                        expect(semverPattern.test(lockfile.version), `Version "${lockfile.version}" is not semver-compatible`).toBeTruthy();
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('generatedAt should be valid ISO timestamp', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.lockfile(),
                    async (lockfile: Lockfile) => {
                        // Property: generatedAt should be parseable as ISO date
                        const date = new Date(lockfile.generatedAt);
                        expect(!isNaN(date.getTime()), `generatedAt "${lockfile.generatedAt}" is not a valid ISO timestamp`).toBeTruthy();
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('bundle entries should have all required fields', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Property: Each bundle entry must have required fields
                        for (const [bundleId, entry] of Object.entries(lockfile.bundles)) {
                            expect(entry.version, `Bundle ${bundleId} missing version`).toBeTruthy();
                            expect(entry.sourceId, `Bundle ${bundleId} missing sourceId`).toBeTruthy();
                            expect(entry.sourceType, `Bundle ${bundleId} missing sourceType`).toBeTruthy();
                            expect(entry.installedAt, `Bundle ${bundleId} missing installedAt`).toBeTruthy();
                            expect(entry.commitMode, `Bundle ${bundleId} missing commitMode`).toBeTruthy();
                            expect(Array.isArray(entry.files), `Bundle ${bundleId} files should be array`).toBeTruthy();
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('file checksums should be valid SHA256 format', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 2 }),
                    async (lockfile: Lockfile) => {
                        // Property: All file checksums should be 64 hex characters
                        const sha256Pattern = /^[a-f0-9]{64}$/;
                        for (const [bundleId, entry] of Object.entries(lockfile.bundles)) {
                            for (const file of entry.files) {
                                expect(sha256Pattern.test(file.checksum), `File ${file.path} in bundle ${bundleId} has invalid checksum format`).toBeTruthy();
                            }
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 3: Lockfile Round-Trip Consistency
     * 
     * For any valid lockfile, reading then writing (without modifications)
     * SHALL produce an equivalent lockfile.
     * 
     * **Validates: Requirements 4.1, 5.2, 5.5**
     */
    describe('Property 3: Lockfile Round-Trip Consistency', () => {
        // Helper to normalize lockfile by removing undefined values (JSON doesn't preserve them)
        const normalizeLockfile = (lockfile: Lockfile): Lockfile => {
            return JSON.parse(JSON.stringify(lockfile));
        };

        it('JSON stringify then parse should preserve lockfile structure', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Property: JSON round-trip should preserve structure
                        // Note: undefined values are not preserved in JSON
                        const serialized = JSON.stringify(lockfile, null, 2);
                        const deserialized = JSON.parse(serialized) as Lockfile;
                        const normalized = normalizeLockfile(lockfile);
                        
                        // Deep equality check (comparing normalized versions)
                        expect(deserialized, 'Round-trip should preserve lockfile structure').toEqual(normalized);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('file write then read should preserve lockfile content', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 2 }),
                    async (lockfile: Lockfile) => {
                        // Property: File I/O round-trip should preserve content
                        const lockfilePath = path.join(tempDir, `lockfile-${Date.now()}.json`);
                        const normalized = normalizeLockfile(lockfile);
                        
                        // Write to file
                        fs.writeFileSync(lockfilePath, JSON.stringify(lockfile, null, 2));
                        
                        // Read back
                        const content = fs.readFileSync(lockfilePath, 'utf8');
                        const readLockfile = JSON.parse(content) as Lockfile;
                        
                        // Verify equality (comparing normalized versions)
                        expect(readLockfile, 'File round-trip should preserve lockfile content').toEqual(normalized);
                        
                        // Cleanup
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });

        it('2-space indentation should be preserved', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 2 }),
                    async (lockfile: Lockfile) => {
                        // Property: 2-space indentation should be used
                        const serialized = JSON.stringify(lockfile, null, 2);
                        
                        // Check for 2-space indentation pattern
                        const lines = serialized.split('\n');
                        const indentedLines = lines.filter(line => line.startsWith('  '));
                        
                        // Should have indented lines if there's content
                        if (Object.keys(lockfile.bundles).length > 0 || Object.keys(lockfile.sources).length > 0) {
                            expect(indentedLines.length > 0, 'Should have 2-space indented lines').toBeTruthy();
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });
    });

    /**
     * Property 15: Atomic Lockfile Write
     * 
     * For any lockfile update operation, the write SHALL be atomic
     * (using temp file + rename pattern) to prevent corruption during
     * concurrent operations or crashes.
     * 
     * **Validates: Requirements 15.6**
     */
    describe('Property 15: Atomic Lockfile Write', () => {
        // Helper to normalize lockfile by removing undefined values (JSON doesn't preserve them)
        const normalizeLockfile = (lockfile: Lockfile): Lockfile => {
            return JSON.parse(JSON.stringify(lockfile));
        };

        it('atomic write pattern should not corrupt existing lockfile on failure', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 2 }),
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 2 }),
                    async (originalLockfile: Lockfile, newLockfile: Lockfile) => {
                        const lockfilePath = path.join(tempDir, `atomic-test-${Date.now()}.json`);
                        const tempPath = lockfilePath + '.tmp';
                        
                        // Normalize to remove undefined values (JSON doesn't preserve them)
                        const normalizedNew = normalizeLockfile(newLockfile);
                        
                        // Write original lockfile
                        fs.writeFileSync(lockfilePath, JSON.stringify(originalLockfile, null, 2));
                        
                        // Simulate atomic write pattern
                        // 1. Write to temp file
                        fs.writeFileSync(tempPath, JSON.stringify(newLockfile, null, 2));
                        
                        // 2. Rename temp to target (atomic on most filesystems)
                        fs.renameSync(tempPath, lockfilePath);
                        
                        // Property: After atomic write, file should contain new content
                        const content = fs.readFileSync(lockfilePath, 'utf8');
                        const readLockfile = JSON.parse(content) as Lockfile;
                        
                        expect(readLockfile, 'Atomic write should result in new lockfile content').toEqual(normalizedNew);
                        
                        // Cleanup
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });

        it('temp file should not exist after successful atomic write', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 2 }),
                    async (lockfile: Lockfile) => {
                        const lockfilePath = path.join(tempDir, `atomic-cleanup-${Date.now()}.json`);
                        const tempPath = lockfilePath + '.tmp';
                        
                        // Simulate atomic write
                        fs.writeFileSync(tempPath, JSON.stringify(lockfile, null, 2));
                        fs.renameSync(tempPath, lockfilePath);
                        
                        // Property: Temp file should not exist after rename
                        expect(fs.existsSync(tempPath), 'Temp file should not exist after atomic write').toBe(false);
                        
                        // Cleanup
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });
    });

    /**
     * Property 7: Checksum Modification Detection
     * 
     * For any installed bundle with recorded checksums, comparing current vs stored
     * checksums SHALL correctly identify modified, missing, and new files.
     * 
     * **Validates: Requirements 14.1-14.3**
     */
    describe('Property 7: Checksum Modification Detection', () => {
        it('identical content should produce identical checksums', async () => {
            await fc.assert(
                fc.asyncProperty(
                    fc.string({ minLength: 1, maxLength: 1000 }),
                    async (content: string) => {
                        // Property: Same content should always produce same checksum
                        const checksum1 = crypto.createHash('sha256').update(content).digest('hex');
                        const checksum2 = crypto.createHash('sha256').update(content).digest('hex');
                        
                        expect(checksum1, 'Identical content should produce identical checksums').toBe(checksum2);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('different content should produce different checksums', async () => {
            await fc.assert(
                fc.asyncProperty(
                    fc.string({ minLength: 1, maxLength: 500 }),
                    fc.string({ minLength: 1, maxLength: 500 }),
                    async (content1: string, content2: string) => {
                        // Skip if contents are identical
                        fc.pre(content1 !== content2);
                        
                        // Property: Different content should produce different checksums
                        const checksum1 = crypto.createHash('sha256').update(content1).digest('hex');
                        const checksum2 = crypto.createHash('sha256').update(content2).digest('hex');
                        
                        expect(checksum1, 'Different content should produce different checksums').not.toBe(checksum2);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('file modification should be detectable via checksum comparison', async () => {
            await fc.assert(
                fc.asyncProperty(
                    fc.string({ minLength: 1, maxLength: 500 }),
                    fc.string({ minLength: 1, maxLength: 500 }),
                    async (originalContent: string, modifiedContent: string) => {
                        // Skip if contents are identical
                        fc.pre(originalContent !== modifiedContent);
                        
                        const filePath = path.join(tempDir, `checksum-test-${Date.now()}.txt`);
                        
                        // Write original content and calculate checksum
                        fs.writeFileSync(filePath, originalContent);
                        const originalChecksum = crypto.createHash('sha256')
                            .update(fs.readFileSync(filePath))
                            .digest('hex');
                        
                        // Modify file
                        fs.writeFileSync(filePath, modifiedContent);
                        const currentChecksum = crypto.createHash('sha256')
                            .update(fs.readFileSync(filePath))
                            .digest('hex');
                        
                        // Property: Modification should be detectable
                        const isModified = originalChecksum !== currentChecksum;
                        expect(isModified, 'File modification should be detectable via checksum').toBe(true);
                        
                        // Cleanup
                        fs.unlinkSync(filePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });

        it('missing file should be detectable', async () => {
            await fc.assert(
                fc.asyncProperty(
                    fc.string({ minLength: 1, maxLength: 100 }),
                    async (content: string) => {
                        const filePath = path.join(tempDir, `missing-test-${Date.now()}.txt`);
                        
                        // Write file and get checksum
                        fs.writeFileSync(filePath, content);
                        const originalChecksum = crypto.createHash('sha256')
                            .update(fs.readFileSync(filePath))
                            .digest('hex');
                        
                        // Delete file
                        fs.unlinkSync(filePath);
                        
                        // Property: Missing file should be detectable
                        const fileExists = fs.existsSync(filePath);
                        expect(fileExists, 'Missing file should be detectable').toBe(false);
                        
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });
    });

    /**
     * Property 12: Source and Hub Configuration Completeness
     * 
     * For any lockfile with bundle entries, corresponding source entries
     * SHALL exist in the sources section.
     * 
     * **Validates: Requirements 12.1-12.6**
     */
    describe('Property 12: Source and Hub Configuration Completeness', () => {
        it('all bundle sourceIds should reference existing sources', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 5 }),
                    async (lockfile: Lockfile) => {
                        // Property: Every bundle's sourceId should exist in sources
                        for (const [bundleId, entry] of Object.entries(lockfile.bundles)) {
                            expect(lockfile.sources[entry.sourceId], `Bundle ${bundleId} references non-existent source ${entry.sourceId}`).toBeTruthy();
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('source entries should have required type and url fields', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Property: All sources should have type and url
                        for (const [sourceId, source] of Object.entries(lockfile.sources)) {
                            expect(source.type, `Source ${sourceId} missing type field`).toBeTruthy();
                            expect(source.url, `Source ${sourceId} missing url field`).toBeTruthy();
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('hub entries should have required name and url fields', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.lockfile({ minBundles: 1, maxBundles: 2, includeHubs: true }),
                    async (lockfile: Lockfile) => {
                        // Property: All hubs should have name and url
                        if (lockfile.hubs) {
                            for (const [hubId, hub] of Object.entries(lockfile.hubs)) {
                                expect(hub.name, `Hub ${hubId} missing name field`).toBeTruthy();
                                expect(hub.url, `Hub ${hubId} missing url field`).toBeTruthy();
                            }
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('profile entries should have required name and bundleIds fields', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.lockfile({ minBundles: 1, maxBundles: 2, includeProfiles: true }),
                    async (lockfile: Lockfile) => {
                        // Property: All profiles should have name and bundleIds
                        if (lockfile.profiles) {
                            for (const [profileId, profile] of Object.entries(lockfile.profiles)) {
                                expect(profile.name, `Profile ${profileId} missing name field`).toBeTruthy();
                                expect(Array.isArray(profile.bundleIds), `Profile ${profileId} bundleIds should be array`).toBeTruthy();
                            }
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('source types should be valid known types', async () => {
            const validSourceTypes = [
                'github', 'gitlab', 'http', 'local',
                'awesome-copilot', 'local-awesome-copilot',
                'apm', 'local-apm', 'olaf', 'local-olaf'
            ];

            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Property: All source types should be valid
                        for (const [sourceId, source] of Object.entries(lockfile.sources)) {
                            expect(validSourceTypes.includes(source.type), `Source ${sourceId} has invalid type: ${source.type}`).toBeTruthy();
                        }
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 3 (Lockfile Source of Truth): LockfileBundleEntry to InstalledBundle Conversion
     * 
     * For any valid LockfileBundleEntry, converting it to InstalledBundle format SHALL produce
     * an object with all required fields (bundleId, version, sourceId, sourceType, installedAt,
     * scope, installPath).
     * 
     * **Validates: Requirements 1.3**
     * 
     * Feature: lockfile-source-of-truth, Property 3: LockfileBundleEntry to InstalledBundle Conversion
     */
    describe('Property 3: LockfileBundleEntry to InstalledBundle Conversion', () => {
        it('converted InstalledBundle should have all required fields', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 5 }),
                    async (lockfile: Lockfile) => {
                        // Write lockfile to temp directory
                        const lockfilePath = path.join(tempDir, 'prompt-registry.lock.json');
                        fs.writeFileSync(lockfilePath, JSON.stringify(lockfile, null, 2));

                        // Get installed bundles using LockfileManager
                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(tempDir);
                        const manager = LockfileManager.getInstance(tempDir);
                        
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: Each converted bundle should have all required fields
                        for (const bundle of installedBundles) {
                            expect(bundle.bundleId, 'Missing bundleId field').toBeTruthy();
                            expect(bundle.version, 'Missing version field').toBeTruthy();
                            expect(bundle.sourceId, 'Missing sourceId field').toBeTruthy();
                            expect(bundle.sourceType, 'Missing sourceType field').toBeTruthy();
                            expect(bundle.installedAt, 'Missing installedAt field').toBeTruthy();
                            expect(bundle.scope, 'Missing scope field').toBeTruthy();
                            expect(bundle.installPath, 'Missing installPath field').toBeTruthy();
                            expect(bundle.manifest, 'Missing manifest field').toBeTruthy();
                        }

                        // Cleanup
                        LockfileManager.resetInstance(tempDir);
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('scope should always be repository for lockfile bundles', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Write lockfile to temp directory
                        const lockfilePath = path.join(tempDir, 'prompt-registry.lock.json');
                        fs.writeFileSync(lockfilePath, JSON.stringify(lockfile, null, 2));

                        // Get installed bundles using LockfileManager
                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(tempDir);
                        const manager = LockfileManager.getInstance(tempDir);
                        
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: All bundles from lockfile should have scope 'repository'
                        for (const bundle of installedBundles) {
                            expect(bundle.scope, `Bundle ${bundle.bundleId} should have scope 'repository', got '${bundle.scope}'`).toBe('repository');
                        }

                        // Cleanup
                        LockfileManager.resetInstance(tempDir);
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('installPath should be constructed from workspace root + .github', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Write lockfile to temp directory
                        const lockfilePath = path.join(tempDir, 'prompt-registry.lock.json');
                        fs.writeFileSync(lockfilePath, JSON.stringify(lockfile, null, 2));

                        // Get installed bundles using LockfileManager
                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(tempDir);
                        const manager = LockfileManager.getInstance(tempDir);
                        
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: installPath should end with .github
                        const expectedPath = path.join(tempDir, '.github');
                        for (const bundle of installedBundles) {
                            expect(bundle.installPath, `Bundle ${bundle.bundleId} installPath should be '${expectedPath}', got '${bundle.installPath}'`).toBe(expectedPath);
                        }

                        // Cleanup
                        LockfileManager.resetInstance(tempDir);
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('version and sourceId should match lockfile entry', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.consistentLockfile({ minBundles: 1, maxBundles: 3 }),
                    async (lockfile: Lockfile) => {
                        // Write lockfile to temp directory
                        const lockfilePath = path.join(tempDir, 'prompt-registry.lock.json');
                        fs.writeFileSync(lockfilePath, JSON.stringify(lockfile, null, 2));

                        // Get installed bundles using LockfileManager
                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(tempDir);
                        const manager = LockfileManager.getInstance(tempDir);
                        
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: version and sourceId should match lockfile entry
                        for (const bundle of installedBundles) {
                            const lockfileEntry = lockfile.bundles[bundle.bundleId];
                            expect(lockfileEntry, `Bundle ${bundle.bundleId} not found in lockfile`).toBeTruthy();
                            expect(bundle.version, `Version mismatch for ${bundle.bundleId}`).toBe(lockfileEntry.version);
                            expect(bundle.sourceId, `SourceId mismatch for ${bundle.bundleId}`).toBe(lockfileEntry.sourceId);
                            expect(bundle.sourceType, `SourceType mismatch for ${bundle.bundleId}`).toBe(lockfileEntry.sourceType);
                            // Note: commitMode is now determined by which lockfile the bundle comes from,
                            // not by the commitMode field in the entry (AD-1: Implicit Commit Mode Based on File Location)
                            // Bundles from main lockfile (prompt-registry.lock.json) always have commitMode: 'commit'
                            expect(bundle.commitMode, `CommitMode for ${bundle.bundleId} should be 'commit' when read from main lockfile`).toBe('commit');
                        }

                        // Cleanup
                        LockfileManager.resetInstance(tempDir);
                        fs.unlinkSync(lockfilePath);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('empty lockfile should return empty array', async () => {
            await fc.assert(
                fc.asyncProperty(
                    fc.constant(null), // No lockfile
                    async () => {
                        // Don't create a lockfile - test that getInstalledBundles returns empty array
                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        const uniqueDir = path.join(tempDir, `empty-${Date.now()}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);
                        
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: No lockfile should return empty array
                        expect(installedBundles.length, 'Should return empty array when lockfile does not exist').toBe(0);

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        fs.rmSync(uniqueDir, { recursive: true, force: true });
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.QUICK
                }
            );
        });
    });
});


/**
 * Lockfile Separation Property Tests
 * 
 * Property-based tests for the dual-lockfile separation feature.
 * These tests verify correctness properties for the local-only lockfile separation.
 * 
 * Properties covered:
 * - Property 1: Lockfile Separation (Requirements 1.1, 1.2)
 * - Property 2: No Duplicate Bundle IDs (Requirement 3.4)
 * - Property 3: Git Exclude Consistency (Requirements 2.1, 2.2)
 * - Property 4: Mode Switching Preserves Metadata (Requirement 4.3)
 * - Property 5: Empty Lockfile Cleanup (Requirements 5.3, 5.4, 5.5)
 * 
 * **Validates: Design Properties 1-5**
 */
describe('Lockfile Separation Properties', () => {
    let tempDir: string;
    const MAIN_LOCKFILE_NAME = 'prompt-registry.lock.json';
    const LOCAL_LOCKFILE_NAME = 'prompt-registry.local.lock.json';

    // ===== Test Utilities =====
    const createTempDir = (): string => {
        const dir = path.join(__dirname, '..', '..', 'test-temp-lockfile-sep-' + Date.now() + '-' + Math.random().toString(36).substring(7));
        fs.mkdirSync(dir, { recursive: true });
        return dir;
    };

    const cleanupTempDir = (dir: string): void => {
        if (fs.existsSync(dir)) {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    };

    const createGitDir = (repoPath: string): void => {
        const gitInfoDir = path.join(repoPath, '.git', 'info');
        fs.mkdirSync(gitInfoDir, { recursive: true });
        fs.writeFileSync(path.join(gitInfoDir, 'exclude'), '# Git exclude file\n');
    };

    const readGitExclude = (repoPath: string): string => {
        const excludePath = path.join(repoPath, '.git', 'info', 'exclude');
        if (fs.existsSync(excludePath)) {
            return fs.readFileSync(excludePath, 'utf-8');
        }
        return '';
    };

    const lockfileExists = (repoPath: string, lockfileName: string): boolean => {
        return fs.existsSync(path.join(repoPath, lockfileName));
    };

    beforeEach(() => {
        tempDir = createTempDir();
    });

    afterEach(async () => {
        // Reset LockfileManager instances
        const { LockfileManager } = await import('../../src/services/LockfileManager');
        LockfileManager.resetInstance(tempDir);
        cleanupTempDir(tempDir);
    });

    /**
     * Property 1: Lockfile Separation
     * 
     * For any bundle creation with a specific commitMode:
     * - commitMode = 'commit' → bundleId ∈ mainLockfile.bundles
     * - commitMode = 'local-only' → bundleId ∈ localLockfile.bundles
     * 
     * **Validates: Requirements 1.1, 1.2**
     */
    describe('Property 1: Lockfile Separation', () => {
        it('bundles with commit mode should be written to main lockfile only', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string) => {
                        const uniqueDir = path.join(tempDir, `commit-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle with commit mode
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode: 'commit',
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Property: Bundle should be in main lockfile
                        const mainLockfilePath = path.join(uniqueDir, MAIN_LOCKFILE_NAME);
                        const localLockfilePath = path.join(uniqueDir, LOCAL_LOCKFILE_NAME);

                        expect(fs.existsSync(mainLockfilePath), 'Main lockfile should exist after creating commit bundle').toBeTruthy();

                        const mainLockfile = JSON.parse(fs.readFileSync(mainLockfilePath, 'utf-8'));
                        expect(mainLockfile.bundles[bundleId], `Bundle ${bundleId} should be in main lockfile`).toBeTruthy();

                        // Property: Bundle should NOT be in local lockfile
                        expect(!fs.existsSync(localLockfilePath), 'Local lockfile should not exist for commit bundles').toBeTruthy();

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('bundles with local-only mode should be written to local lockfile only', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string) => {
                        const uniqueDir = path.join(tempDir, `local-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle with local-only mode
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode: 'local-only',
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Property: Bundle should be in local lockfile
                        const mainLockfilePath = path.join(uniqueDir, MAIN_LOCKFILE_NAME);
                        const localLockfilePath = path.join(uniqueDir, LOCAL_LOCKFILE_NAME);

                        expect(fs.existsSync(localLockfilePath), 'Local lockfile should exist after creating local-only bundle').toBeTruthy();

                        const localLockfile = JSON.parse(fs.readFileSync(localLockfilePath, 'utf-8'));
                        expect(localLockfile.bundles[bundleId], `Bundle ${bundleId} should be in local lockfile`).toBeTruthy();

                        // Property: Bundle should NOT be in main lockfile
                        expect(!fs.existsSync(mainLockfilePath), 'Main lockfile should not exist when only local-only bundles are installed').toBeTruthy();

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 2: No Duplicate Bundle IDs
     * 
     * For any bundleId: ¬(bundleId ∈ mainLockfile.bundles ∧ bundleId ∈ localLockfile.bundles)
     * 
     * A bundle ID can only exist in one lockfile at a time.
     * 
     * **Validates: Requirement 3.4**
     */
    describe('Property 2: No Duplicate Bundle IDs', () => {
        it('bundle ID can only exist in one lockfile at a time after mode switch', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    LockfileGenerators.commitMode(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string, initialMode) => {
                        const uniqueDir = path.join(tempDir, `nodupe-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle with initial mode
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode: initialMode,
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Switch to opposite mode
                        const newMode = initialMode === 'commit' ? 'local-only' : 'commit';
                        await manager.updateCommitMode(bundleId, newMode);

                        // Property: Bundle should exist in exactly one lockfile
                        const mainLockfilePath = path.join(uniqueDir, MAIN_LOCKFILE_NAME);
                        const localLockfilePath = path.join(uniqueDir, LOCAL_LOCKFILE_NAME);

                        const mainExists = fs.existsSync(mainLockfilePath);
                        const localExists = fs.existsSync(localLockfilePath);

                        let inMain = false;
                        let inLocal = false;

                        if (mainExists) {
                            const mainLockfile = JSON.parse(fs.readFileSync(mainLockfilePath, 'utf-8'));
                            inMain = !!mainLockfile.bundles[bundleId];
                        }

                        if (localExists) {
                            const localLockfile = JSON.parse(fs.readFileSync(localLockfilePath, 'utf-8'));
                            inLocal = !!localLockfile.bundles[bundleId];
                        }

                        // Property: Bundle should be in exactly one lockfile (XOR)
                        expect((inMain && !inLocal) || (!inMain && inLocal), `Bundle ${bundleId} should exist in exactly one lockfile. In main: ${inMain}, In local: ${inLocal}`).toBeTruthy();

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 3: Bundles from main lockfile always have commitMode 'commit' when listed
     * 
     * When listing bundles, bundles from the main lockfile should always have
     * commitMode: 'commit' set on them.
     * 
     * **Validates: Requirement 3.3**
     */
    describe('Property 3: Commit Mode Annotation from Main Lockfile', () => {
        it('bundles from main lockfile always have commitMode commit when listed', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string) => {
                        const uniqueDir = path.join(tempDir, `main-mode-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle with commit mode
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode: 'commit',
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Get installed bundles
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: Bundle from main lockfile should have commitMode 'commit'
                        const bundle = installedBundles.find(b => b.bundleId === bundleId);
                        expect(bundle, `Bundle ${bundleId} should be in installed bundles`).toBeTruthy();
                        expect(bundle!.commitMode, `Bundle ${bundleId} from main lockfile should have commitMode 'commit'`).toBe('commit');

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 4: Bundles from local lockfile always have commitMode 'local-only' when listed
     * 
     * When listing bundles, bundles from the local lockfile should always have
     * commitMode: 'local-only' set on them.
     * 
     * **Validates: Requirement 3.2**
     */
    describe('Property 4: Commit Mode Annotation from Local Lockfile', () => {
        it('bundles from local lockfile always have commitMode local-only when listed', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string) => {
                        const uniqueDir = path.join(tempDir, `local-mode-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle with local-only mode
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode: 'local-only',
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Get installed bundles
                        const installedBundles = await manager.getInstalledBundles();

                        // Property: Bundle from local lockfile should have commitMode 'local-only'
                        const bundle = installedBundles.find(b => b.bundleId === bundleId);
                        expect(bundle, `Bundle ${bundleId} should be in installed bundles`).toBeTruthy();
                        expect(bundle!.commitMode, `Bundle ${bundleId} from local lockfile should have commitMode 'local-only'`).toBe('local-only');

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 5: Mode Switching Preserves Metadata
     * 
     * For any bundle, switching commit mode should preserve all metadata:
     * - version
     * - sourceId
     * - sourceType
     * - files
     * - checksum (if present)
     * 
     * **Validates: Requirement 4.3**
     */
    describe('Property 5: Mode Switching Preserves Metadata', () => {
        it('mode switching preserves all bundle metadata', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    fc.array(LockfileGenerators.fileEntry(), { minLength: 0, maxLength: 3 }),
                    LockfileGenerators.commitMode(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string, files, initialMode) => {
                        const uniqueDir = path.join(tempDir, `preserve-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle with initial mode
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode: initialMode,
                            files,
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Get original bundle data
                        const originalBundles = await manager.getInstalledBundles();
                        const originalBundle = originalBundles.find(b => b.bundleId === bundleId);
                        expect(originalBundle, 'Original bundle should exist').toBeTruthy();

                        // Switch to opposite mode
                        const newMode = initialMode === 'commit' ? 'local-only' : 'commit';
                        await manager.updateCommitMode(bundleId, newMode);

                        // Get bundle after mode switch
                        const updatedBundles = await manager.getInstalledBundles();
                        const updatedBundle = updatedBundles.find(b => b.bundleId === bundleId);
                        expect(updatedBundle, 'Updated bundle should exist').toBeTruthy();

                        // Property: All metadata should be preserved
                        expect(updatedBundle!.version, 'Version should be preserved after mode switch').toBe(originalBundle!.version);
                        expect(updatedBundle!.sourceId, 'SourceId should be preserved after mode switch').toBe(originalBundle!.sourceId);
                        expect(updatedBundle!.sourceType, 'SourceType should be preserved after mode switch').toBe(originalBundle!.sourceType);

                        // Property: Commit mode should be updated
                        expect(updatedBundle!.commitMode, `CommitMode should be updated to ${newMode}`).toBe(newMode);

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });

    /**
     * Property 6: Empty Lockfile Cleanup
     * 
     * For any lockfile (main or local):
     * |lockfile.bundles| = 0 → ¬fileExists(lockfile.path)
     * 
     * When a lockfile becomes empty (no bundles), it should be deleted.
     * 
     * **Validates: Requirements 5.3, 5.5**
     */
    describe('Property 6: Empty Lockfile Cleanup', () => {
        it('empty lockfile is deleted after removing last bundle', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    LockfileGenerators.commitMode(),
                    async (bundleId: string, version: string, sourceId: string, sourceType: string, commitMode) => {
                        const uniqueDir = path.join(tempDir, `empty-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create bundle
                        await manager.createOrUpdate({
                            bundleId,
                            version,
                            sourceId,
                            sourceType,
                            commitMode,
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Verify lockfile exists
                        const lockfileName = commitMode === 'local-only' ? LOCAL_LOCKFILE_NAME : MAIN_LOCKFILE_NAME;
                        const lockfilePath = path.join(uniqueDir, lockfileName);
                        expect(fs.existsSync(lockfilePath), `Lockfile ${lockfileName} should exist after creating bundle`).toBeTruthy();

                        // Remove the bundle
                        await manager.remove(bundleId);

                        // Property: Empty lockfile should be deleted
                        expect(!fs.existsSync(lockfilePath), `Lockfile ${lockfileName} should be deleted after removing last bundle`).toBeTruthy();

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });

        it('lockfile with remaining bundles is not deleted', async () => {
            await fc.assert(
                fc.asyncProperty(
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.bundleId(),
                    LockfileGenerators.version(),
                    LockfileGenerators.sourceId(),
                    LockfileGenerators.sourceType(),
                    LockfileGenerators.commitMode(),
                    async (bundleId1: string, bundleId2: string, version: string, sourceId: string, sourceType: string, commitMode) => {
                        // Ensure bundle IDs are different
                        fc.pre(bundleId1 !== bundleId2);

                        const uniqueDir = path.join(tempDir, `remain-${Date.now()}-${Math.random().toString(36).substring(7)}`);
                        fs.mkdirSync(uniqueDir, { recursive: true });
                        createGitDir(uniqueDir);

                        const { LockfileManager } = await import('../../src/services/LockfileManager');
                        LockfileManager.resetInstance(uniqueDir);
                        const manager = LockfileManager.getInstance(uniqueDir);

                        // Create two bundles with same commit mode
                        await manager.createOrUpdate({
                            bundleId: bundleId1,
                            version,
                            sourceId,
                            sourceType,
                            commitMode,
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        await manager.createOrUpdate({
                            bundleId: bundleId2,
                            version,
                            sourceId,
                            sourceType,
                            commitMode,
                            files: [],
                            source: { type: sourceType, url: `https://example.com/${sourceId}` }
                        });

                        // Remove one bundle
                        await manager.remove(bundleId1);

                        // Property: Lockfile should still exist with remaining bundle
                        const lockfileName = commitMode === 'local-only' ? LOCAL_LOCKFILE_NAME : MAIN_LOCKFILE_NAME;
                        const lockfilePath = path.join(uniqueDir, lockfileName);
                        expect(fs.existsSync(lockfilePath), `Lockfile ${lockfileName} should still exist with remaining bundle`).toBeTruthy();

                        const lockfile = JSON.parse(fs.readFileSync(lockfilePath, 'utf-8'));
                        expect(lockfile.bundles[bundleId2], `Bundle ${bundleId2} should still be in lockfile`).toBeTruthy();
                        expect(!lockfile.bundles[bundleId1], `Bundle ${bundleId1} should be removed from lockfile`).toBeTruthy();

                        // Cleanup
                        LockfileManager.resetInstance(uniqueDir);
                        cleanupTempDir(uniqueDir);
                        return true;
                    }
                ),
                {
                    ...PropertyTestConfig.FAST_CHECK_OPTIONS,
                    numRuns: PropertyTestConfig.RUNS.STANDARD
                }
            );
        });
    });
});
